import type { NextConfig } from "next";

const nextConfig: NextConfig = {
  serverExternalPackages: ['mongoose', 'mongodb', 'isomorphic-dompurify', 'jsdom', 'cheerio', 'markdown-it'],
  images: {
    remotePatterns: [
      {
        protocol: 'https',
        hostname: 'wsyhnifiqkc8fvyw.public.blob.vercel-storage.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '*.agoda.net',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '*.agoda.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '*.bstatic.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: '*.booking.com',
        port: '',
        pathname: '/**',
      },
      {
        protocol: 'https',
        hostname: 'images.unsplash.com',
        port: '',
        pathname: '/**',
      },
    ],
  },
  async redirects() {
    return [
      {
        source: '/usa/new-york-city',
        destination: '/usa/new-york',
        permanent: true,
      },
      {
        source: '/usa/new%20york',
        destination: '/usa/new-york',
        permanent: true,
      },
      // Legacy city URL formats → canonical /country/city paths
      // These were indexed by Google under old URL structures and split ranking authority
      { source: '/hotels-with-bathtub-in-new-delhi', destination: '/india/delhi', permanent: true },
      { source: '/hotels-with-bathtub-in-new-delhi/', destination: '/india/delhi', permanent: true },
      { source: '/hotels-with-bathtub-in-bangalore', destination: '/india/bangalore', permanent: true },
      { source: '/hotels-with-bathtub-in-bangalore/', destination: '/india/bangalore', permanent: true },
      { source: '/hotels-with-bathtub-in-jaipur', destination: '/india/jaipur', permanent: true },
      { source: '/hotels-with-bathtub-in-jaipur/', destination: '/india/jaipur', permanent: true },
      { source: '/hotels-with-bathtub-in-ahmedabad', destination: '/india/ahmedabad', permanent: true },
      { source: '/hotels-with-bathtub-in-ahmedabad/', destination: '/india/ahmedabad', permanent: true },
      { source: '/hotels-with-bathtub-in-pune', destination: '/india/pune', permanent: true },
      { source: '/hotels-with-bathtub-in-pune/', destination: '/india/pune', permanent: true },
      { source: '/hotels-with-bathtub-in-kolkata', destination: '/india/kolkata', permanent: true },
      { source: '/hotels-with-bathtub-in-kolkata/', destination: '/india/kolkata', permanent: true },
      { source: '/hotels-with-bathtub-in-mumbai', destination: '/india/mumbai', permanent: true },
      { source: '/hotels-with-bathtub-in-mumbai/', destination: '/india/mumbai', permanent: true },
      { source: '/hotels-with-bathtub-in-goa', destination: '/india/goa', permanent: true },
      { source: '/hotels-with-bathtub-in-goa/', destination: '/india/goa', permanent: true },
      { source: '/hotels-with-bathtub-in-manali', destination: '/india/manali', permanent: true },
      { source: '/hotels-with-bathtub-in-manali/', destination: '/india/manali', permanent: true },
      { source: '/hotels-with-bathtub-in-shimla', destination: '/india/shimla', permanent: true },
      { source: '/hotels-with-bathtub-in-shimla/', destination: '/india/shimla', permanent: true },
      { source: '/hotels-with-bathtub-in-udaipur', destination: '/india/udaipur', permanent: true },
      { source: '/hotels-with-bathtub-in-udaipur/', destination: '/india/udaipur', permanent: true },
      { source: '/hotels-with-bathtub-in-lonavala', destination: '/india/lonavala', permanent: true },
      { source: '/hotels-with-bathtub-in-lonavala/', destination: '/india/lonavala', permanent: true },
      { source: '/hotels-with-bathtub-in-munnar', destination: '/india/munnar', permanent: true },
      { source: '/hotels-with-bathtub-in-munnar/', destination: '/india/munnar', permanent: true },
      { source: '/hotels-with-bathtub-in-gurgaon', destination: '/india/gurgaon', permanent: true },
      { source: '/hotels-with-bathtub-in-gurgaon/', destination: '/india/gurgaon', permanent: true },
      { source: '/hotels-with-bathtub-in-chandigarh', destination: '/india/chandigarh', permanent: true },
      { source: '/hotels-with-bathtub-in-chandigarh/', destination: '/india/chandigarh', permanent: true },
      { source: '/hotels-with-bathtub-in-gandhinagar', destination: '/india/gandhinagar', permanent: true },
      { source: '/hotels-with-bathtub-in-gandhinagar/', destination: '/india/gandhinagar', permanent: true },
      { source: '/hotels-with-bathtub-in-ooty', destination: '/india/ooty', permanent: true },
      { source: '/hotels-with-bathtub-in-ooty/', destination: '/india/ooty', permanent: true },

      // Naked city legacy paths → canonical /india/[city]
      { source: '/agra', destination: '/india/agra', permanent: true },
      { source: '/agra/', destination: '/india/agra', permanent: true },
      { source: '/amritsar', destination: '/india/amritsar', permanent: true },
      { source: '/amritsar/', destination: '/india/amritsar', permanent: true },
      { source: '/bhopal', destination: '/india/bhopal', permanent: true },
      { source: '/bhopal/', destination: '/india/bhopal', permanent: true },
      { source: '/chandigarh', destination: '/india/chandigarh', permanent: true },
      { source: '/chandigarh/', destination: '/india/chandigarh', permanent: true },
      { source: '/coimbatore', destination: '/india/coimbatore', permanent: true },
      { source: '/coimbatore/', destination: '/india/coimbatore', permanent: true },
      { source: '/daman', destination: '/india/daman', permanent: true },
      { source: '/daman/', destination: '/india/daman', permanent: true },
      { source: '/darjeeling', destination: '/india/darjeeling', permanent: true },
      { source: '/darjeeling/', destination: '/india/darjeeling', permanent: true },
      { source: '/dharamshala', destination: '/india/dharamshala', permanent: true },
      { source: '/dharamshala/', destination: '/india/dharamshala', permanent: true },
      { source: '/digha', destination: '/india/digha', permanent: true },
      { source: '/digha/', destination: '/india/digha', permanent: true },
      { source: '/faridabad', destination: '/india/faridabad', permanent: true },
      { source: '/faridabad/', destination: '/india/faridabad', permanent: true },
      { source: '/gandhinagar', destination: '/india/gandhinagar', permanent: true },
      { source: '/gandhinagar/', destination: '/india/gandhinagar', permanent: true },
      { source: '/gurgaon', destination: '/india/gurgaon', permanent: true },
      { source: '/gurgaon/', destination: '/india/gurgaon', permanent: true },
      { source: '/haridwar', destination: '/india/haridwar', permanent: true },
      { source: '/haridwar/', destination: '/india/haridwar', permanent: true },
      { source: '/igatpuri', destination: '/india/igatpuri', permanent: true },
      { source: '/igatpuri/', destination: '/india/igatpuri', permanent: true },
      { source: '/indore', destination: '/india/indore', permanent: true },
      { source: '/indore/', destination: '/india/indore', permanent: true },
      { source: '/jaipur', destination: '/india/jaipur', permanent: true },
      { source: '/jaipur/', destination: '/india/jaipur', permanent: true },
      { source: '/karjat', destination: '/india/karjat', permanent: true },
      { source: '/karjat/', destination: '/india/karjat', permanent: true },
      { source: '/kochi', destination: '/india/kochi', permanent: true },
      { source: '/kochi/', destination: '/india/kochi', permanent: true },
      { source: '/kodaikanal', destination: '/india/kodaikanal', permanent: true },
      { source: '/kodaikanal/', destination: '/india/kodaikanal', permanent: true },
      { source: '/kolhapur', destination: '/india/kolhapur', permanent: true },
      { source: '/kolhapur/', destination: '/india/kolhapur', permanent: true },
      { source: '/kolkata', destination: '/india/kolkata', permanent: true },
      { source: '/kolkata/', destination: '/india/kolkata', permanent: true },
      { source: '/lavasa', destination: '/india/lavasa', permanent: true },
      { source: '/lavasa/', destination: '/india/lavasa', permanent: true },
      { source: '/lonavala', destination: '/india/lonavala', permanent: true },
      { source: '/lonavala/', destination: '/india/lonavala', permanent: true },
      { source: '/mahabalipuram', destination: '/india/mahabalipuram', permanent: true },
      { source: '/mahabalipuram/', destination: '/india/mahabalipuram', permanent: true },
      { source: '/manali', destination: '/india/manali', permanent: true },
      { source: '/manali/', destination: '/india/manali', permanent: true },
      { source: '/mandarmani', destination: '/india/mandarmani', permanent: true },
      { source: '/mandarmani/', destination: '/india/mandarmani', permanent: true },
      { source: '/mathura', destination: '/india/mathura', permanent: true },
      { source: '/mathura/', destination: '/india/mathura', permanent: true },
      { source: '/mount-abu', destination: '/india/mount-abu', permanent: true },
      { source: '/mount-abu/', destination: '/india/mount-abu', permanent: true },
      { source: '/mumbai', destination: '/india/mumbai', permanent: true },
      { source: '/mumbai/', destination: '/india/mumbai', permanent: true },
      { source: '/munnar', destination: '/india/munnar', permanent: true },
      { source: '/munnar/', destination: '/india/munnar', permanent: true },
      { source: '/nainital', destination: '/india/nainital', permanent: true },
      { source: '/nainital/', destination: '/india/nainital', permanent: true },
      { source: '/nashik', destination: '/india/nashik', permanent: true },
      { source: '/nashik/', destination: '/india/nashik', permanent: true },
      { source: '/ooty', destination: '/india/ooty', permanent: true },
      { source: '/ooty/', destination: '/india/ooty', permanent: true },
      { source: '/panchgani', destination: '/india/panchgani', permanent: true },
      { source: '/panchgani/', destination: '/india/panchgani', permanent: true },
      { source: '/panvel', destination: '/india/panvel', permanent: true },
      { source: '/panvel/', destination: '/india/panvel', permanent: true },
      { source: '/pune', destination: '/india/pune', permanent: true },
      { source: '/pune/', destination: '/india/pune', permanent: true },
      { source: '/puri', destination: '/india/puri', permanent: true },
      { source: '/puri/', destination: '/india/puri', permanent: true },
      { source: '/rajkot', destination: '/india/rajkot', permanent: true },
      { source: '/rajkot/', destination: '/india/rajkot', permanent: true },
      { source: '/rishikesh', destination: '/india/rishikesh', permanent: true },
      { source: '/rishikesh/', destination: '/india/rishikesh', permanent: true },
      { source: '/saputara', destination: '/india/saputara', permanent: true },
      { source: '/saputara/', destination: '/india/saputara', permanent: true },
      { source: '/shillong', destination: '/india/shillong', permanent: true },
      { source: '/shillong/', destination: '/india/shillong', permanent: true },
      { source: '/shimla', destination: '/india/shimla', permanent: true },
      { source: '/shimla/', destination: '/india/shimla', permanent: true },
      { source: '/shirdi', destination: '/india/shirdi', permanent: true },
      { source: '/shirdi/', destination: '/india/shirdi', permanent: true },
      { source: '/siliguri', destination: '/india/siliguri', permanent: true },
      { source: '/siliguri/', destination: '/india/siliguri', permanent: true },
      { source: '/udaipur', destination: '/india/udaipur', permanent: true },
      { source: '/udaipur/', destination: '/india/udaipur', permanent: true },
      { source: '/yercaud', destination: '/india/yercaud', permanent: true },
      { source: '/yercaud/', destination: '/india/yercaud', permanent: true },
      { source: '/zirakpur', destination: '/india/zirakpur', permanent: true },
      { source: '/zirakpur/', destination: '/india/zirakpur', permanent: true },

      // Regional neighborhood consolidation redirects
      { source: '/india/calangute', destination: '/india/goa', permanent: true },
      { source: '/india/calangute/', destination: '/india/goa', permanent: true },
      { source: '/calangute', destination: '/india/goa', permanent: true },
      { source: '/calangute/', destination: '/india/goa', permanent: true },
      { source: '/india/panjim', destination: '/india/goa', permanent: true },
      { source: '/india/panjim/', destination: '/india/goa', permanent: true },
      { source: '/panjim', destination: '/india/goa', permanent: true },
      { source: '/panjim/', destination: '/india/goa', permanent: true },
      { source: '/india/koramangala', destination: '/india/bangalore', permanent: true },
      { source: '/india/koramangala/', destination: '/india/bangalore', permanent: true },
      { source: '/koramangala', destination: '/india/bangalore', permanent: true },
      { source: '/koramangala/', destination: '/india/bangalore', permanent: true },
      { source: '/india/mahipalpur', destination: '/india/delhi', permanent: true },
      { source: '/india/mahipalpur/', destination: '/india/delhi', permanent: true },
      { source: '/mahipalpur', destination: '/india/delhi', permanent: true },
      { source: '/mahipalpur/', destination: '/india/delhi', permanent: true },
      { source: '/india/paharganj', destination: '/india/delhi', permanent: true },
      { source: '/india/paharganj/', destination: '/india/delhi', permanent: true },
      { source: '/paharganj', destination: '/india/delhi', permanent: true },
      { source: '/paharganj/', destination: '/india/delhi', permanent: true },
      // Blog slug aliases & historical redirects
      {
        source: '/blog/verify-hotel-amenities',
        destination: '/blog/verify-hotel-amenities-accurate-booking',
        permanent: true,
      },
      {
        source: '/blog/budget-romantic-trips-india',
        destination: '/blog/budget-romantic-getaway-india',
        permanent: true,
      },
      {
        source: '/blog/honeymoon-hotels-bathtubs',
        destination: '/blog/honeymoon-hotels-freestanding-bathtubs-india',
        permanent: true,
      },
      {
        source: '/blog/how-verification-works',
        destination: '/#verification',
        permanent: true,
      },
      {
        source: '/blog/luxury-couple-hotels-india-cities',
        destination: '/blog/best-hotels-private-jacuzzi-couples-india',
        permanent: true,
      },
    ];
  },
};

export default nextConfig;
