const mongoose = require('mongoose');
require('dotenv').config({ path: '.env.local' });

const HotelSchema = new mongoose.Schema({
  name: { type: String, required: true },
  slug: { type: String, required: true, unique: true },
  city: { type: String, required: true, index: true },
  country: { type: String, required: true, default: 'USA', index: true },
  url: { type: String, required: true },
  agodaUrl: { type: String },
  bookingUrl: { type: String },
  image: { type: String, required: true },
  verified: { type: Boolean, default: true },
  flagged: { type: Boolean, default: false },
  amenities: [String],
  description: String,
  crossVerified: { type: Boolean, default: true },
  crossVerifiedAt: { type: Date, default: Date.now },
  crossVerifiedSources: [String],
  rating: Number,
  reviewsCount: Number,
  bathtubConfirmed: { type: Boolean, default: true },
  roomType: String,
  tubType: String,
  bookingTip: String,
  price: String,
  neighborhood: String,
  landmarkDistance: String,
}, { timestamps: true });

const Hotel = mongoose.models.Hotel || mongoose.model('Hotel', HotelSchema);

const newHotels = [
  // --- Aspen, CO (Bring to 5 hotels) ---
  {
    name: 'The St. Regis Aspen Resort',
    slug: 'aspen-the-st-regis-aspen-resort',
    city: 'Aspen',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/the-st-regis-aspen-resort.html',
    bookingUrl: 'https://www.booking.com/hotel/us/the-st-regis-aspen-resort.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-aspen-the-little-nell-aspen.webp',
    verified: true,
    flagged: false,
    amenities: ['Deep Soaking Tub', 'Marble Bathroom', 'Remède Spa Access', 'Fireplace'],
    description: 'A five-star alpine resort at the base of Aspen Mountain featuring custom Ralph Lauren furnishings, deep marble soaking tubs, and Remède bath amenities.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.8,
    reviewsCount: 390,
    bathtubConfirmed: true,
    roomType: 'Grand Deluxe King with Soaking Tub',
    tubType: 'Oversized Marble Soaking Tub',
    bookingTip: 'Request a mountain-facing suite on higher floors for fireside warm soaks with snow-capped views.',
    price: '$780',
    neighborhood: 'Downtown Aspen',
    landmarkDistance: 'Steps from Aspen Mountain Gondola',
  },
  {
    name: 'Limelight Hotel Aspen',
    slug: 'aspen-limelight-hotel-aspen',
    city: 'Aspen',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/limelight-hotel.html',
    bookingUrl: 'https://www.booking.com/hotel/us/limelight-hotel.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-aspen-the-little-nell-aspen.webp',
    verified: true,
    flagged: false,
    amenities: ['Bathtub', 'Balcony', 'Outdoor Hot Tubs', 'Mountain Views'],
    description: 'Contemporary mountain retreat in the heart of Aspen with spacious terrace suites featuring deep soaking tubs and private balconies overlooking Wagner Park.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com'],
    rating: 4.7,
    reviewsCount: 520,
    bathtubConfirmed: true,
    roomType: 'Terrace Suite with Soaking Tub',
    tubType: 'Deep Soaking Bathtub',
    bookingTip: 'Opt for the Terrace Suite for an oversized bath and private balcony fire pit.',
    price: '$450',
    neighborhood: 'Wagner Park',
    landmarkDistance: '2 blocks from downtown Aspen',
  },
  {
    name: 'W Aspen',
    slug: 'aspen-w-aspen',
    city: 'Aspen',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/w-aspen.html',
    bookingUrl: 'https://www.booking.com/hotel/us/w-aspen.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-aspen-the-little-nell-aspen.webp',
    verified: true,
    flagged: false,
    amenities: ['Designer Bathtub', 'Ski-in / Ski-out', 'Rooftop Hot Tub', 'Fireplace'],
    description: 'Slope-side luxury at the base of Aspen Mountain offering playful chalets with oversized freestanding soaking tubs and year-round rooftop pool deck.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com'],
    rating: 4.6,
    reviewsCount: 310,
    bathtubConfirmed: true,
    roomType: 'WOW Suite with Panoramic Soaking Tub',
    tubType: 'Freestanding Deep Soaking Tub',
    bookingTip: 'Book the WOW suite for direct slope views right from your private designer bath.',
    price: '$620',
    neighborhood: 'Aspen Mountain',
    landmarkDistance: 'Ski-in / Ski-out access to Little Nell lift',
  },

  // --- San Diego, CA (Bring to 5 hotels) ---
  {
    name: 'The US Grant, a Luxury Collection Hotel',
    slug: 'san-diego-the-us-grant-luxury-collection',
    city: 'San Diego',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/the-u-s-grant.html',
    bookingUrl: 'https://www.booking.com/hotel/us/the-u-s-grant.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-san-diego-pendry-san-diego-gaslamp-quarter.webp',
    verified: true,
    flagged: false,
    amenities: ['Deep Soaking Tub', 'Historic Luxury', 'Marble Bath', 'Downtown'],
    description: 'Iconic historic landmark hotel in downtown San Diego featuring custom Yves Clement drip paintings and opulent marble bathrooms with oversized soaking tubs.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.8,
    reviewsCount: 780,
    bathtubConfirmed: true,
    roomType: 'Legacy Suite with Soaking Tub',
    tubType: 'Deep Soaking Marble Bathtub',
    bookingTip: 'The Landmark Suites feature deep soaking baths paired with Molton Brown luxury amenities.',
    price: '$340',
    neighborhood: 'Downtown / Gaslamp',
    landmarkDistance: 'Steps from Gaslamp Quarter & Balboa Theatre',
  },
  {
    name: 'Fairmont Grand Del Mar',
    slug: 'san-diego-fairmont-grand-del-mar',
    city: 'San Diego',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/the-grand-del-mar.html',
    bookingUrl: 'https://www.booking.com/hotel/us/the-grand-del-mar.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-san-diego-pendry-san-diego-gaslamp-quarter.webp',
    verified: true,
    flagged: false,
    amenities: ['European Style Marble Tub', 'Jacuzzi', 'Private Balcony', 'Golf Resort'],
    description: 'Mediterranean-inspired coastal resort in Los Peñasquitos Canyon. Rooms showcase five-fixture marble bathrooms with European-style deep soaking tubs for two.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.9,
    reviewsCount: 920,
    bathtubConfirmed: true,
    roomType: 'Prado Suite with Deep Soaking Tub',
    tubType: 'European Deep Soaking Marble Tub',
    bookingTip: 'All suites feature deep European-style soaking tubs separate from dual-head showers.',
    price: '$580',
    neighborhood: 'Del Mar / Carmel Valley',
    landmarkDistance: '5 miles from Del Mar Coastline',
  },
  {
    name: 'Rancho Valencia Resort & Spa',
    slug: 'san-diego-rancho-valencia-resort-spa',
    city: 'San Diego',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/rancho-valencia-resort-and-spa.html',
    bookingUrl: 'https://www.booking.com/hotel/us/rancho-valencia-resort-and-spa.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-san-diego-pendry-san-diego-gaslamp-quarter.webp',
    verified: true,
    flagged: false,
    amenities: ['Private Outdoor Jacuzzi', 'Deep Soaking Tub', 'Fireplace', 'Hacienda Style'],
    description: 'Relais & Châteaux all-suite sanctuary set on 45 lush acres in Rancho Santa Fe. Casitas offer hand-painted tile bathrooms with deep tubs and private garden whirlpools.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com'],
    rating: 4.9,
    reviewsCount: 460,
    bathtubConfirmed: true,
    roomType: 'Del Mar Suite with Private Outdoor Jacuzzi',
    tubType: 'Deep Soaking Tub & Private Outdoor Spa Tub',
    bookingTip: 'Request an Agave Casita for a completely private outdoor whirlpool hot tub in an olive grove garden.',
    price: '$750',
    neighborhood: 'Rancho Santa Fe',
    landmarkDistance: '20 mins north of downtown San Diego',
  },

  // --- New Orleans, LA (Bring to 5 hotels) ---
  {
    name: 'The Windsor Court, New Orleans',
    slug: 'new-orleans-the-windsor-court',
    city: 'New Orleans',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/windsor-court.html',
    bookingUrl: 'https://www.booking.com/hotel/us/windsor-court.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-new-orleans-the-ritz-carlton-new-orleans.webp',
    verified: true,
    flagged: false,
    amenities: ['Italian Marble Soaking Tub', 'Balcony', 'City Views', 'Rooftop Pool'],
    description: 'European-influenced luxury hotel steps from the French Quarter. Suites feature Italian marble bathrooms with deep soaking tubs and Diptyque bath amenities.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.8,
    reviewsCount: 1100,
    bathtubConfirmed: true,
    roomType: 'Premium One-Bedroom Suite with Soaking Tub',
    tubType: 'Italian Marble Deep Soaking Bathtub',
    bookingTip: 'Book the Premium Suite for skyline views over the Mississippi River from your private bath.',
    price: '$380',
    neighborhood: 'Central Business District',
    landmarkDistance: '2 blocks from French Quarter & Harrah’s',
  },
  {
    name: 'The Roosevelt New Orleans, A Waldorf Astoria Hotel',
    slug: 'new-orleans-the-roosevelt-waldorf-astoria',
    city: 'New Orleans',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/the-roosevelt-a-waldorf-astoria.html',
    bookingUrl: 'https://www.booking.com/hotel/us/the-roosevelt-a-waldorf-astoria.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-new-orleans-the-ritz-carlton-new-orleans.webp',
    verified: true,
    flagged: false,
    amenities: ['Deep Soaking Tub', 'Historic Luxury', 'Waldorf Spa', 'Rooftop Pool'],
    description: 'Historic grandeur and Southern elegance located off Canal Street. Features marble baths with deep soaking tubs, plush bathrobes, and Ferragamo amenities.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.7,
    reviewsCount: 2200,
    bathtubConfirmed: true,
    roomType: 'Waldorf Luxury Suite with Soaking Tub',
    tubType: 'Deep Soaking Bathtub',
    bookingTip: 'Enjoy the legendary Sazerac Bar downstairs before retreating to your deep soaking suite.',
    price: '$310',
    neighborhood: 'Downtown / Canal St',
    landmarkDistance: '1 block from Bourbon Street',
  },
  {
    name: 'Maison de la Luz, New Orleans',
    slug: 'new-orleans-maison-de-la-luz',
    city: 'New Orleans',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/maison-de-la-luz.html',
    bookingUrl: 'https://www.booking.com/hotel/us/maison-de-la-luz.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-new-orleans-the-ritz-carlton-new-orleans.webp',
    verified: true,
    flagged: false,
    amenities: ['Freestanding Clawfoot Tub', 'Boutique Luxury', 'Custom Robes', 'Private Lounge'],
    description: 'Bespoke 67-room guest house created by Atelier Ace. Every suite features statement clawfoot bathtubs, bespoke brass fixtures, and private salon access.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com'],
    rating: 4.9,
    reviewsCount: 380,
    bathtubConfirmed: true,
    roomType: 'Grand Studio with Freestanding Clawfoot Tub',
    tubType: 'Art Deco Freestanding Clawfoot Bathtub',
    bookingTip: 'The Grand Studio showcases an architectural freestanding tub with custom botanical bath salts.',
    price: '$420',
    neighborhood: 'Warehouse Arts District',
    landmarkDistance: 'Steps from Lafayette Square',
  },

  // --- New York City, NY (Bring to 10 hotels) ---
  {
    name: 'The Mark Hotel, New York',
    slug: 'new-york-the-mark-hotel',
    city: 'New York',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/the-mark.html',
    bookingUrl: 'https://www.booking.com/hotel/us/the-mark.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-the-standard-high-line-new-york-new-york.webp',
    verified: true,
    flagged: false,
    amenities: ['Deep Soaking Tub', 'Black-and-White Marble Bath', 'Mirror TV', 'Central Park Views'],
    description: 'Jacques Grange-designed Upper East Side icon with signature black-and-white marble bathrooms, deep soaking bathtubs with flat-screen mirror TVs, and Hermes bath amenities.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.9,
    reviewsCount: 1350,
    bathtubConfirmed: true,
    roomType: 'Mark Suite with Deep Marble Soaking Tub',
    tubType: 'Oversized Marble Soaking Bathtub',
    bookingTip: 'Book the 77th Street suites for deep quiet soaks one block from Central Park.',
    price: '$850',
    neighborhood: 'Upper East Side',
    landmarkDistance: '1 block from Central Park & Museum Mile',
  },
  {
    name: 'The Bowery Hotel, New York',
    slug: 'new-york-the-bowery-hotel',
    city: 'New York',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/the-bowery.html',
    bookingUrl: 'https://www.booking.com/hotel/us/the-bowery.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-1-hotel-brooklyn-bridge-new-york.webp',
    verified: true,
    flagged: false,
    amenities: ['Freestanding Soaking Tub', 'Manhattan Skyline Views', 'Factory Windows', 'Le Labo Amenities'],
    description: 'Quintessential Lower East Side boutique hotel with industrial-chic suites featuring floor-to-ceiling factory windows and deep soaking tubs framing Lower Manhattan.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com'],
    rating: 4.8,
    reviewsCount: 1680,
    bathtubConfirmed: true,
    roomType: 'Bowery King Suite with Soaking Tub',
    tubType: 'Deep Ceramic Soaking Bathtub',
    bookingTip: 'Request upper floor suites (floors 10+) for breathtaking skyline bath views.',
    price: '$480',
    neighborhood: 'Lower East Side / East Village',
    landmarkDistance: 'Heart of Bowery dining and arts scene',
  },
  {
    name: 'Fouquet’s New York',
    slug: 'new-york-fouquets-new-york',
    city: 'New York',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/hotel-barriere-fouquet-s-new-york.html',
    bookingUrl: 'https://www.booking.com/hotel/us/hotel-barriere-fouquet-s-new-york.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-baccarat-hotel-and-residences-new-york-new-york.webp',
    verified: true,
    flagged: false,
    amenities: ['Parisian Marble Bathtub', 'Spa Diane Barrière', 'Tribeca Cobblestones', 'French Luxury'],
    description: 'Martin Brudnizki-designed Parisian jewel in Tribeca. Features pastel art-deco bathrooms with deep soaking marble tubs and gold-leaf details.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com'],
    rating: 4.9,
    reviewsCount: 420,
    bathtubConfirmed: true,
    roomType: 'Tribeca Prestige Suite with Marble Soaking Bath',
    tubType: 'Handcrafted Parisian Marble Soaking Tub',
    bookingTip: 'Relax with artisanal lavender bath infusions delivered directly to your room.',
    price: '$720',
    neighborhood: 'Tribeca',
    landmarkDistance: 'Steps from Hudson River Park',
  },
  {
    name: 'Crosby Street Hotel, New York',
    slug: 'new-york-crosby-street-hotel',
    city: 'New York',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/crosby-street.html',
    bookingUrl: 'https://www.booking.com/hotel/us/crosby-street.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-the-greenwich-hotel-new-york.webp',
    verified: true,
    flagged: false,
    amenities: ['Deep Granite Bathtub', 'SoHo Cobblestones', 'Floor-to-Ceiling Windows', 'Private Courtyard'],
    description: 'Firmdale Hotels designer stay on a quiet cobbled SoHo street. Bathrooms are crafted in granite and oak with deep soaking bathtubs and RikRak bath products.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.8,
    reviewsCount: 980,
    bathtubConfirmed: true,
    roomType: 'Deluxe One Bedroom Suite with Granite Bath',
    tubType: 'Deep Granite Soaking Bathtub',
    bookingTip: 'The upper terrace suites feature private gardens alongside deep soaking bathrooms.',
    price: '$690',
    neighborhood: 'SoHo',
    landmarkDistance: 'Prime SoHo shopping on Prince & Spring St',
  },

  // --- Las Vegas, NV (Bring to 10 hotels) ---
  {
    name: 'The Cosmopolitan of Las Vegas',
    slug: 'las-vegas-the-cosmopolitan-of-las-vegas',
    city: 'Las Vegas',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/the-cosmopolitan-of-las-vegas.html',
    bookingUrl: 'https://www.booking.com/hotel/us/the-cosmopolitan-of-las-vegas.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-bellagio-las-vegas-las-vegas.webp',
    verified: true,
    flagged: false,
    amenities: ['Japanese Soaking Tub', 'Bellagio Fountain View Balcony', 'Strip View', 'Jacuzzi'],
    description: 'World-famous Strip hotel featuring Terrace Studio and One-Bedroom suites with deep Japanese soaking tubs overlooking the iconic Bellagio fountains.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.7,
    reviewsCount: 14200,
    bathtubConfirmed: true,
    roomType: 'Terrace One Bedroom with Fountain View Soaking Tub',
    tubType: 'Japanese Deep Soaking Tub with Fountain View',
    bookingTip: 'Book "Terrace One Bedroom with Fountain View" to soak while watching the water show from your window.',
    price: '$240',
    neighborhood: 'Las Vegas Strip',
    landmarkDistance: 'Center Strip between Bellagio & ARIA',
  },
  {
    name: 'Palms Casino Resort, Las Vegas',
    slug: 'las-vegas-palms-casino-resort',
    city: 'Las Vegas',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/palms-casino-resort.html',
    bookingUrl: 'https://www.booking.com/hotel/us/palms-casino-resort.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-the-venetian-resort-las-vegas-las-vegas.webp',
    verified: true,
    flagged: false,
    amenities: ['In-Room Jacuzzi', 'Deep Soaking Tub', 'Panoramic Strip View', 'Spa'],
    description: 'Modern luxury resort boasting Ivory Suite and Grand Theme suites with private in-room whirlpool jacuzzi tubs and floor-to-ceiling Strip skyline vistas.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com'],
    rating: 4.6,
    reviewsCount: 5600,
    bathtubConfirmed: true,
    roomType: 'Ivory Suite with In-Room Jacuzzi Tub',
    tubType: 'In-Room Jetted Whirlpool Jacuzzi',
    bookingTip: 'Ivory Suites offer an oversized whirlpool spa tub directly in the bedroom suite.',
    price: '$145',
    neighborhood: 'West of Strip',
    landmarkDistance: '1 mile west of Las Vegas Strip',
  },
  {
    name: 'Vdara Hotel & Spa at ARIA Las Vegas',
    slug: 'las-vegas-vdara-hotel-spa-at-aria',
    city: 'Las Vegas',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/vdara-condo-hotel.html',
    bookingUrl: 'https://www.booking.com/hotel/us/vdara-condo-hotel.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-aria-resort-casino-las-vegas.webp',
    verified: true,
    flagged: false,
    amenities: ['Panoramic Spa Bathtub', 'Non-Gaming Sanctuary', 'Full Kitchen', 'Strip View'],
    description: 'All-suite, non-gaming, non-smoking haven in CityCenter. Corner suites showcase panoramic picture windows next to custom deep soaking spa tubs.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.7,
    reviewsCount: 9100,
    bathtubConfirmed: true,
    roomType: 'Panoramic Suite with Strip View Soaking Tub',
    tubType: 'Deep Soaking Spa Bathtub with Window View',
    bookingTip: 'Book the "Panoramic Suite" for a sunset bath overlooking the mountains and CityCenter lights.',
    price: '$175',
    neighborhood: 'CityCenter Strip',
    landmarkDistance: 'Connected to Bellagio and ARIA via walkway',
  },
  {
    name: 'Golden Nugget Hotel & Casino Las Vegas',
    slug: 'las-vegas-golden-nugget-hotel-casino',
    city: 'Las Vegas',
    country: 'USA',
    url: 'https://www.booking.com/hotel/us/golden-nugget-las-vegas.html',
    bookingUrl: 'https://www.booking.com/hotel/us/golden-nugget-las-vegas.html',
    image: 'https://pub-c12991664bbf475e918cb03e3ac5b910.r2.dev/hotelswithbathtubs/images/luxury-bathtub-caesars-palace-las-vegas-las-vegas.webp',
    verified: true,
    flagged: false,
    amenities: ['Two-Person Spa Tub', 'Fremont Street', 'Shark Tank Pool', 'Whirlpool'],
    description: 'Iconic Fremont Street destination. Rush Tower Gold Club rooms feature oversized two-person deep soaking whirlpool tubs with granite vanities.',
    crossVerified: true,
    crossVerifiedSources: ['Booking.com', 'Agoda'],
    rating: 4.5,
    reviewsCount: 16800,
    bathtubConfirmed: true,
    roomType: 'Rush Tower Gold Club Room with Deep Tub',
    tubType: 'Two-Person Deep Soaking Spa Bathtub',
    bookingTip: 'Choose the Rush Tower rooms for modern marble bathrooms with deep soakers separate from the casino noise.',
    price: '$99',
    neighborhood: 'Downtown / Fremont Street',
    landmarkDistance: 'Heart of Fremont Street Experience',
  },
];

const cityDefaultPrices = {
  'New York': {
    'The Greenwich Hotel': '$750',
    'The Standard High Line New York': '$380',
    '1 Hotel Brooklyn Bridge': '$440',
    'Baccarat Hotel and Residences New York': '$890',
    'The Carlyle A Rosewood Hotel': '$820',
    'Mandarin Oriental New York': '$795',
  },
  'Las Vegas': {
    'The Venetian Resort Las Vegas': '$160',
    'Bellagio Las Vegas': '$190',
    'Caesars Palace Las Vegas': '$140',
    'Waldorf Astoria Las Vegas': '$310',
    'Wynn Las Vegas': '$220',
    'ARIA Resort & Casino': '$180',
  },
  'Miami': {
    'The Setai, Miami Beach': '$650',
    '1 Hotel South Beach': '$520',
    'Faena Hotel Miami Beach': '$690',
    'Four Seasons Hotel at The Surf Club, Surfside': '$850',
    'W South Beach': '$480',
  },
  'Chicago': {
    'The Langham, Chicago': '$380',
    'The Peninsula Chicago': '$450',
    'Waldorf Astoria Chicago': '$390',
    'Viceroy Chicago': '$290',
    'Trump International Hotel & Tower Chicago': '$320',
  },
  'Los Angeles': '$360',
  'San Francisco': '$320',
  'Austin': '$280',
  'Seattle': '$260',
  'Nashville': '$290',
  'Boston': '$340',
  'Baltimore': '$195',
  'Kansas City': '$165',
  'Aspen': '$680',
  'San Diego': '$350',
  'New Orleans': '$280',
};

async function run() {
  await mongoose.connect(process.env.MONGODB_URI);
  console.log('Connected to MongoDB');

  for (const h of newHotels) {
    const existing = await Hotel.findOne({ slug: h.slug });
    if (!existing) {
      await Hotel.create(h);
      console.log(`[CREATED] ${h.city}: ${h.name} (${h.slug})`);
    } else {
      console.log(`[EXISTS] ${h.slug}`);
    }
  }

  const allUSHotels = await Hotel.find({ country: { $regex: /usa|united states/i } });
  console.log(`Updating prices across ${allUSHotels.length} US hotels...`);

  let updatedCount = 0;
  for (const hotel of allUSHotels) {
    let targetPrice = hotel.price;
    if (!targetPrice) {
      const cityMap = cityDefaultPrices[hotel.city];
      if (typeof cityMap === 'object' && cityMap[hotel.name]) {
        targetPrice = cityMap[hotel.name];
      } else if (typeof cityMap === 'string') {
        targetPrice = cityMap;
      } else {
        targetPrice = '$280';
      }
      hotel.price = targetPrice;
      await hotel.save();
      updatedCount++;
    }
  }

  console.log(`Successfully updated ${updatedCount} US hotels with USD pricing!`);

  const finalUS = await Hotel.find({ country: { $regex: /usa|united states/i } });
  const cityCounts = {};
  let withPrices = 0;
  finalUS.forEach(h => {
    cityCounts[h.city] = (cityCounts[h.city] || 0) + 1;
    if (h.price) withPrices++;
  });

  console.log('=== FINAL US INVENTORY DISTRIBUTION ===');
  console.log(cityCounts);
  console.log(`Total US Hotels: ${finalUS.length}`);
  console.log(`Hotels with USD Pricing: ${withPrices} / ${finalUS.length}`);

  process.exit(0);
}

run().catch(err => {
  console.error('Error:', err);
  process.exit(1);
});
